const obj = {
  services: [
    {
      service: 0,
      serviceType: 0,
      title: "Resume Services",
      short: "",
      long: "",
      notes: "",
      services: [3, 4, 5, 6, 7],
      questions: [0, 5, 6, 7, 8, 9, 10],
    },
    {
      service: 1,
      serviceType: 0,
      title: "Resume Services",
      short: 'Exculisve to Clients who availed the "New Resume Service"',
      long: "",
      notes: "",
      services: [3, 4, 5, 6, 7],
      questions: [0, 5, 6, 7, 8, 9, 10],
    },
    {
      service: 2,
      serviceType: 0,
      title: "Resume Services",
      short: "",
      long: "",
      notes: "",
      services: [3, 4, 5, 6, 7, 8, 9],
      questions: [0, 5, 6, 7, 8, 9, 10],
    },
    {
      service: 3,
      serviceType: 1,
      title: "Other Services",
      short: "Government / Public Sector",
      long: "",
      notes: "",
      services: [],
      questions: [1, 2, 3, 5, 6, 7, 8, 9, 10],
    },
    {
      service: 4,
      serviceType: 1,
      title: "Other Services",
      short: "Private Sector",
      long: "",
      notes: "",
      services: [],
      questions: [1, 2, 3, 5, 6, 7, 8, 9, 10],
    },
    {
      service: 5,
      serviceType: 1,
      title: "Other Services",
      short: "Government / Public Sector",
      long: "",
      notes: "",
      services: [],
      questions: [1, 2, 3, 5, 6, 7, 8, 9, 10],
    },
    {
      service: 6,
      serviceType: 1,
      title: "Other Services",
      short:
        "A customised Selection Criteria highlighting your qualities, skills, abilities and knowledge",
      long: "Key selection criteria (KSC) are typically used in the Australian Public Sector by Government agencies across all levels, from Local and State to Federal, as well as in the education and not-for-profit sector. A well-written, correctly structured selection criteria statement that showcases your skills, knowledge, qualifications and achievements is your key to getting noticed and securing an interview.\r\n\r\nEach selection criteria that we write is customised for you and to the role. We use appropriate keywords and specific examples that accurately respond to the questions, while taking into account the role description and the Integrated Leadership System (ILS), which is the APS capability framework. When responding to the selection criteria, we make sure that each answer is maximum half a page long (in between 250-300 words), as the selection panel often has limited time to go through every applicant.",
      notes: "",
      services: [],
      questions: [4, 5, 6, 7, 8, 9, 10],
    },
    {
      service: 7,
      serviceType: 2,
      title: "Other Services",
      short: "",
      long: "",
      notes: "",
      services: [],
      questions: [],
    },
    {
      service: 8,
      serviceType: 2,
      title: "",
      short: "",
      long: "",
      notes: "",
      services: [],
      questions: [],
    },
    {
      service: 9,
      serviceType: 2,
      title: "",
      short: "",
      long: "",
      notes: "",
      services: [],
      questions: [],
    },
  ],
  questions: [
    {
      question: 0,
      questionType: 0,
      notes: [
        "Include all jobs (e.g., roles in irrelevant sectors or industries, overseas experience, part-time, contract, casual, project-based).",
        "For Nursing/Social Work, include placements",
      ],
      responses: [0, 1, 2],
    },
    {
      question: 1,
      questionType: 1,
      notes: [""],
      responses: [3, 4, 15],
    },
    {
      question: 2,
      questionType: 2,
      notes: [""],
      responses: [5, 6, 7, 8],
    },
    {
      question: 3,
      questionType: 2,
      notes: [""],
      responses: [9, 10, 11, 12, 13],
    },
    {
      question: 4,
      questionType: 1,
      notes: [""],
      responses: [5, 6, 7, 20, 21],
    },
    {
      question: 5,
      questionType: 0,
      notes: [""],
      responses: [14, 15],
    },
    {
      question: 6,
      questionType: 0,
      notes: [""],
      responses: [14, 15],
    },
    {
      question: 7,
      questionType: 0,
      notes: [""],
      responses: [14, 15],
    },
    {
      question: 8,
      questionType: 0,
      notes: [""],
      responses: [14, 15],
    },
    {
      question: 9,
      questionType: 3,
      notes: [""],
      responses: [],
    },
    {
      question: 10,
      questionType: 3,
      notes: [""],
      responses: [16, 17, 18, 19],
    },
  ],
  responses: [
    {
      reponses: 0,
      followup: [],
    },
    {
      reponses: 1,
      followup: [],
    },
    {
      reponses: 2,
      followup: [],
    },
    {
      reponses: 3,
      followup: [2],
    },
    {
      reponses: 4,
      followup: [3],
    },
    {
      reponses: 5,
      followup: [],
    },
    {
      reponses: 6,
      followup: [],
    },
    {
      reponses: 7,
      followup: [],
    },
    {
      reponses: 8,
      followup: [],
    },
    {
      reponses: 9,
      followup: [],
    },
    {
      reponses: 10,
      followup: [],
    },
    {
      reponses: 11,
      followup: [],
    },
    {
      reponses: 12,
      followup: [],
    },
    {
      reponses: 13,
      followup: [],
    },
    {
      reponses: 14,
      followup: [],
    },
    {
      reponses: 15,
      followup: [],
    },
    {
      reponses: 16,
      followup: [],
    },
    {
      reponses: 17,
      followup: [],
    },
    {
      reponses: 18,
      followup: [],
    },
    {
      reponses: 19,
      followup: [],
    },
    {
      reponses: 20,
      followup: [],
    },
    {
      reponses: 21,
      followup: [],
    },
  ],
  indices: {
    serviceType: ["Resume", "Other", "Addon"],
    serviceList: [
      "New Resume",
      "Resume Editing",
      "Resume Update",
      "Pitch / Statement of Claims / Response Document",
      "Cover Letter 1",
      "Cover Letter 2",
      "Selection Criteria",
      "LinkedIn Profile (Add-on only)",
      "LinkedIn Profile Update (Add-on only)",
      "Cover Letter  Update (Add-on only)",
    ],
    questionType: ["Generic", "Specific", "Followup", "Closing"],
    questionList: [
      "How many years of experience do you have in total?",
      "Is there a page or word limit to your cover letter, pitch, statement or response?",
      "What is the page limit?",
      "What is the word limit?",
      "How many selection criteria do you need responses to?",
      "Is your current job in? retail, hospitality, trades, services and/or admin support?",
      "Have you had experience supervising or managing staff?",
      "Are you a senior leader, C-level executive, GM, Director, EL, SES?",
      "Are you a Doctor, Lawyer or Engineer?",
      "How soon do you need the final copy of your documents?",
      "Please fill out the form below to receive your quotation. ",
    ],
    responseList: [
      "Less Than 2 Years",
      "2-5 Years",
      "More than 5",
      "Yes, page limit",
      "Yes, word limit",
      "One (1)",
      "Two (2)",
      "Three (3)",
      "More Than Three",
      "500 and Below",
      "600 - 1,000",
      "1,100 - 1,500",
      "1,600 - 2,000",
      "2,000 - Above",
      "Yes",
      "No",
      "Enter a date",
      "First Name:",
      "Family Name:",
      "Email:",
      "Four (4)",
      "Five (5)",
    ],
    responseType: ["Radio", "Checkbox", "Number", "Text", "Date"],
  },
};
